name = "tagCustom48h12"
min_hamming = 12
min_complexity = 12

[layout]
type = "custom"
grid_size = 10
data = "dddddddddddbbbbbbbbddbwwwwwwbddbwddddwbddbwdxxdwbddbwdxxdwbddbwddddwbddbwwwwwwbddbbbbbbbbddddddddddd"
